# Used to deploy the app fully locally, including a VS Code dev environment
name: DND Toolkit - Dev

services:
  ui:
    image: dnd-toolkit-ui:dev
    container_name: ui_ember_dnd_toolkit
    build:
      context: ./ui
      dockerfile: Dockerfile
    user: pnpm
    working_dir: /home/pnpm/app
    entrypoint: ["./ui/docker-entrypoint.sh"]
    command: pnpm run -r start
    environment:
      - PNPM_HOME=/home/pnpm
    ports:
      - 4200:4200
    volumes:
      - pnpm-store:/home/pnpm/store
      - pnpm-global-store:/home/pnpm/global
      - pnpm-global-bin:/home/pnpm/bin
      - type: bind
        source: .
        target: /home/pnpm/app

  dev:
    image: dnd-toolkit-dev:dev
    # Prevent trying to find the image in a registry
    pull_policy: never
    container_name: dev_vscode_dnd_toolkit
    build:
      context: .
      dockerfile: Dockerfile.vscode
    entrypoint: ["./docker-entrypoint.sh"]
    working_dir: /home/pnpm/app
    command: sleep infinity
    stop_grace_period: 3s
    environment:
      - PNPM_HOME=/home/pnpm
    volumes:
      - bash-history:/command-history
      - pnpm-store:/home/pnpm/store
      - pnpm-global-store:/home/pnpm/global
      - pnpm-global-bin:/home/pnpm/bin
      - type: bind
        source: .
        target: /home/pnpm/app

volumes:
  bash-history:
  pnpm-store:
  pnpm-global-store:
  pnpm-global-bin:
